#   .----------------.
#  | .--------------. |
#  | | ____   ____  | |
#  | ||_  _| |_  _| | |
#  | |  \ \   / /   | |
#  | |   \ \ / /    | |
#  | |    \ ' /     | |
#  | |     \_/      | |
#  | |              | |
#  | '--------------' |
#   '----------------'
# Vilicus is a server-management tool for Minecraft: Java Edition.
# Author: Cooper Sullivan (https://github.com/coopersully/vilicus)

# Server API Update Settings
server_api:
  # Enable automatic checking and installation of server API updates.
  auto_update: true
  # Specify the server version to use: set a specific version (e.g., "1.20.4") or "latest" for continuous updates.
  preferred_version: "latest"

# Plugin Management
update_plugin_names: true
# Enable automatic organization of your plugins directory. This renames all plugins to the format "NAME-VERSION.jar".

# Server Launch Settings
on_launch:
  # Memory Management Settings
  heap:
    # Initial heap size in megabytes. Determines the starting memory allocation pool.
    initial: 5012
    # Maximum heap size in megabytes. Limits the memory allocation pool's growth.
    maximum: 5012

  # Java Virtual Machine (JVM) flags for the server startup script.
  flags:
    # Predefined flags are set based on the heap settings. Additional flags can be specified below.
    - "-Dterminal.jline=false"
    - "-Dterminal.ansi=true"
    - "-XX:+UseG1GC"
    - "-XX:+ParallelRefProcEnabled"
    - "-XX:MaxGCPauseMillis=200"
    - "-XX:+UnlockExperimentalVMOptions"
    - "-XX:+DisableExplicitGC"
    - "-XX:+AlwaysPreTouch"
    - "-XX:G1HeapWastePercent=5"
    - "-XX:G1MixedGCCountTarget=4"
    - "-XX:G1MixedGCLiveThresholdPercent=90"
    - "-XX:G1RSetUpdatingPauseTimePercent=5"
    - "-XX:SurvivorRatio=32"
    - "-XX:+PerfDisableSharedMem"
    - "-XX:MaxTenuringThreshold=1"
    - "-XX:G1NewSizePercent=30"
    - "-XX:G1MaxNewSizePercent=40"
    - "-XX:G1HeapRegionSize=8M"
    - "-XX:G1ReservePercent=20"
    - "-XX:InitiatingHeapOccupancyPercent=15"
    - "-Dusing.aikars.flags=https://mcflags.emc.gs"
    - "-Daikars.new.flags=true"
    - "--add-modules=jdk.incubator.vector"

# Log File Management
log_management:
  enable_auto_delete: true
  # Enable automatic deletion of log files older than a specified number of days.
  retention_days: 60
  # Number of days to retain log files before they are automatically deleted.
